### PR TITLE
use callback and not channels for shard syncing

### LINKED ISSUE #168: Deadline for heartbeat ack is too low
**Describe the bug**
DisGord has hardcoded a 3 second deadline.

**Expected behavior**
Disgord should check before sending the next heartbeat if one was recieved for the previous heartbeat.

### PR DESCRIPTION
**Pull request by andersfylling**
# Description

Removes channels and uses easy to understand callbacks for rate limiting connecting to the ws gateway.

affects #162 #132 
fixes #168

### CODE REVIEW

File: websocket/client.go [hunk 1]
```diff
@@ -722,56 +629,50 @@ func (c *client) prepareHeartbeating(ctx context.Context) {
...
+		lastAck = c.lastHeartbeatAck
+		lastSent = c.lastHeartbeatSent
 		c.RUnlock()
 
-		if err := c.behaviors[heartbeating].actions[sendHeartbeat](nil); err != nil {
-			c.Error(err)
+		// make sure that Discord replied to the last heartbeat signal (heartbeat ack)
+		if lastSent.After(lastAck) {
+			c.log.Info(c.getLogPrefix(), "heartbeat ACK was not received, forcing reconnect")
+			go c.reconnect()
```
Comment (golangcibot) [inline websocket/client.go]: Error return value of `c.reconnect` is not checked (from `errcheck`)

File: websocket/sharding.go [hunk 2]
```diff
@@ -80,11 +117,14 @@ type ShardManagerConfig struct {
...
-	mu             sync.RWMutex
-	conf           ShardManagerConfig
-	shards         map[shardID]*EvtClient
-	DiscordPktPool *sync.Pool
-	A              A
+	mu                       sync.RWMutex
+	conf                     ShardManagerConfig
+	shards                   map[shardID]*EvtClient
+	DiscordPktPool           *sync.Pool
+	nextAllowedIdentity      time.Time
```
Comment (golangcibot) [inline websocket/sharding.go]: `nextAllowedIdentity` is unused (from `structcheck`)

File: websocket/sharding.go [hunk 3]
```diff
@@ -80,11 +117,14 @@ type ShardManagerConfig struct {
...
+	nextAllowedIdentityMutex sync.Mutex
```
Comment (golangcibot) [inline websocket/sharding.go]: `nextAllowedIdentityMutex` is unused (from `structcheck`)

File: websocket/client.go [hunk 4]
```diff
@@ -96,6 +99,12 @@ type config struct {
 	// for testing only
 	conn Conn
 
+	// connect is blocking until a websocket connection has completed it's setup.
+	// eg. Normal shards that handles events are considered connected once the
+	// identity/resume has been sent. While for voice we wait until a ready event
+	// is returned.
+	connect connectSignature
```
Comment (golangcibot) [inline websocket/client.go]: `connect` is unused (from `structcheck`)

File: websocket/eventclient_test.go [hunk 5]
```diff
@@ -250,17 +242,23 @@ func TestEvtClient_reconnect(t *testing.T) {
 		t.Error("timeout")
 	}(t)
 
+	wg2 := sync.WaitGroup{}
+	wg2.Add(1)
+	go func() {
+		// send hello packet
+		wg[heartbeat].Add(1)
```
Comment (golangcibot) [inline websocket/eventclient_test.go]: SA2000: should call wg[heartbeat].Add(1) before starting the goroutine to avoid a race (from `staticcheck`)

File: websocket/shard_sync.go [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+
+	s.logger.Debug("shard", shardID, "will wait in connect queue for", delay)
+	select {
+	case <-time.After(delay):
+		s.logger.Debug("shard", shardID, "waited", delay, "and is now being connected")
+		start := time.Now()
+		if err := cb(); err != nil {
+			return err
+		}
+		execDuration := time.Now().Sub(start)
```
Comment (golangcibot) [inline websocket/shard_sync.go]: S1012: should use `time.Since` instead of `time.Now().Sub` (from `gosimple`)

File: websocket/client.go [hunk 7]
```diff
@@ -597,7 +513,9 @@ func (c *client) emitter(ctx context.Context) {
 		saveOutgoingPacket(c, msg)
 
 		if err = c.conn.WriteJSON(msg); err != nil {
-			c.Error(err)
+			c.log.Error(c.getLogPrefix(), err)
+			cancel()
+			go c.reconnect()
```
Comment (golangcibot) [inline websocket/client.go]: Error return value of `c.reconnect` is not checked (from `errcheck`)

File: websocket/client.go [hunk 8]
```diff
@@ -567,26 +479,30 @@ func (c *client) unlockEmitter() {
...
 	if !c.lockEmitter() {
-		c.Debug("tried to startBehaviors another websocket emitter go routine")
+		c.log.Debug(c.getLogPrefix(), "tried to startBehaviors another websocket emitter go routine")
 		return
 	}
 	defer c.unlockEmitter()
-	c.Debug("starting emitter")
+	c.log.Debug(c.getLogPrefix(), "starting emitter")
 
+	internal, cancel := context.WithCancel(context.Background())
```
Comment (golangcibot) [inline websocket/client.go]: lostcancel: the cancel function is not used on all paths (possible context leak) (from `govet`)

File: websocket/client.go [hunk 9]
```diff
@@ -567,26 +479,30 @@ func (c *client) unlockEmitter() {
...
 	for {
 		var msg *clientPacket
 		var open bool
 
 		select {
 		case <-ctx.Done():
-			c.Debug("closing emitter")
+			c.log.Debug(c.getLogPrefix(), "closing emitter")
+			return
```
Comment (golangcibot) [inline websocket/client.go]: lostcancel: this return statement may be reached without using the cancel var defined on line 488 (from `govet`)

File: websocket/eventclient.go [hunk 10]
```diff
@@ -407,22 +364,87 @@ func (c *EvtClient) sendHeartbeat(i interface{}) error {
...
+		if err := c.openConnection(); err != nil {
+			return err
+		}
+
+		c.log.Debug(c.getLogPrefix(), "waiting to send identify/resume")
+		select {
+		case <-sentIdentifyResume:
+		case <-time.After(3 * time.Minute):
+			c.log.Error(c.getLogPrefix(), "discord timeout during connect (3 minutes). No idea what went wrong..")
+			go c.reconnect()
```
Comment (golangcibot) [inline websocket/eventclient.go]: Error return value of `c.reconnect` is not checked (from `errcheck`)

File: websocket/client.go [hunk 11]
```diff
@@ -567,28 +484,34 @@ func (c *client) unlockEmitter() {
...
 		var msg *clientPacket
 		var open bool
 
 		select {
 		case <-ctx.Done():
-			c.Debug("closing emitter")
+			c.log.Debug(c.getLogPrefix(), "closing emitter")
 			return
+		case <-internal.Done():
+			go c.reconnect()
```
Comment (golangcibot) [inline websocket/client.go]: Error return value of `c.reconnect` is not checked (from `errcheck`)

File: websocket/client.go [hunk 12]
```diff
@@ -634,19 +558,32 @@ func (c *client) unlockReceiver() {
...
 
+	internal, cancel := context.WithCancel(context.Background())
 	for {
+		// check if application has closed
+		select {
+		case <-ctx.Done():
+			c.log.Debug(c.getLogPrefix(), "closing receiver")
+			return
+		case <-internal.Done():
+			go c.reconnect()
```
Comment (golangcibot) [inline websocket/client.go]: Error return value of `c.reconnect` is not checked (from `errcheck`)

File: websocket/client.go [hunk 13]
```diff
@@ -634,19 +558,32 @@ func (c *client) unlockReceiver() {
...
 	if !c.lockReceiver() {
-		c.Debug("tried to start another receiver")
+		c.log.Debug(c.getLogPrefix(), "tried to start another receiver")
 		return
 	}
 	defer c.unlockReceiver()
-	c.Debug("starting receiver")
+	c.log.Debug(c.getLogPrefix(), "starting receiver")
 
+	internal, cancel := context.WithCancel(context.Background())
```
Comment (golangcibot) [inline websocket/client.go]: lostcancel: the cancel function is not used on all paths (possible context leak) (from `govet`)

File: websocket/client.go [hunk 14]
```diff
@@ -634,19 +558,32 @@ func (c *client) unlockReceiver() {
...
 	for {
+		// check if application has closed
+		select {
+		case <-ctx.Done():
+			c.log.Debug(c.getLogPrefix(), "closing receiver")
+			return
```
Comment (golangcibot) [inline websocket/client.go]: lostcancel: this return statement may be reached without using the cancel var defined on line 567 (from `govet`)

File: websocket/client.go [hunk 15]
```diff
@@ -205,159 +215,66 @@ func (c *client) startBehaviors(ctx context.Context) {
...
+		} else {
+			c.log.Debug(c.getLogPrefix(), "tried calling undefined discord operation", p.Op)
 		}
 
 		// see receiver() for creation/Get()
 		c.poolDiscordPkt.Put(p)
 	}
 }
 
+func (c *client) inactivityDetector() {
```
Comment (golangcibot) [inline websocket/client.go]: U1000: func `(*client).inactivityDetector` is unused (from `unused`)
